FROM golang:1.17-alpine AS build

WORKDIR /app
# COPY . .
# RUN go mod tidy
# RUN go build -o app

# COPY *.go .
# RUN go build -o app

COPY go.sum . 
COPY go.mod .
RUN go mod download

COPY *.go .
RUN go build -o app

FROM alpine:latest
COPY --from=build /app/app /app

EXPOSE 8080
CMD ["/app"]
